name: Generate Customized Image

on: [push]

env:
  image_name: my_image.img
  hostname: $hostname

jobs:
  generate-customized-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Gather secrets
        run: python3 src/gather_secrets.py

      - name: Render template
        run: python3 src/template_renderer.py
        env:
          HOSTNAME: ${{ secrets[format('{0}', env.host_name)] }}
          USERNAME: ${{ secrets[format('{0}', env.user_name)] }}
          USERNAMEPASSWORD: ${{ secrets[format('{0}', env.user_name_password)] }}
          WIFISSID: ${{ secrets[format('{0}', env.wifi_ssid)] }}
          WIFIPASSWORD: ${{ secrets[format('{0}', env.wifi_password)] }}
          SSHPUBLICKEY: ${{ secrets[format('{0}', env.ssh_public_key)] }}

      - name: Image Fetcher
        run: python3 src/image_fetcher.py

      - name: Check if image is downloaded and decompressed
        run: tree

      - name: Run script
        run: sudo sh ./src/scripts/customize_image.sh

      - name: Upload data to artifactory
        uses: actions/upload-artifact@v3
        with:
          name: Rasp_custom_image
          path: 2023-02-21-raspios-buster-armhf-lite.img
