name: Hello-World

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello World"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test if repo is check-out
        run: tree